# Generated by Django 4.2 on 2023-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
