# Generated by Django 4.2.1 on 2023-06-19 18:27

import AppDjango.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0003_record_userprofile_competitor_medal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medal',
            old_name='count',
            new_name='bronce',
        ),
        migrations.RemoveField(
            model_name='medal',
            name='medal',
        ),
        migrations.AddField(
            model_name='medal',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medal',
            name='siler',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academy',
            name='styles',
            field=models.ManyToManyField(related_name='academies', to='AppDjango.style'),
        ),
        migrations.RemoveField(
            model_name='medal',
            name='style',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='styles',
            field=models.ManyToManyField(default=AppDjango.models.Style.allowed_styles, related_name='users', to='AppDjango.style'),
        ),
        migrations.AddField(
            model_name='medal',
            name='style',
            field=models.ManyToManyField(related_name='medals', to='AppDjango.style'),
        ),
    ]
