# Generated by Django 4.2.1 on 2023-06-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0004_rename_count_medal_bronce_remove_medal_medal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medal',
            old_name='siler',
            new_name='silver',
        ),
    ]
