# Generated by Django 4.2.1 on 2023-08-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0007_remove_userprofile_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='styles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDjango.style'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='amateur_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amateur_record', to='AppDjango.record'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='professional_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional_record', to='AppDjango.record'),
        ),
    ]
