# Generated by Django 4.2.1 on 2023-08-31 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0008_userprofile_styles_alter_userprofile_amateur_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medal',
            old_name='bronce',
            new_name='bronze',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medals',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDjango.medal'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='styles',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='styles',
            field=models.ManyToManyField(blank=True, to='AppDjango.style'),
        ),
    ]
