# Generated by Django 4.2.1 on 2023-09-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0009_rename_bronce_medal_bronze_alter_userprofile_medals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('Karate', 'Karate'), ('Judo', 'Judo'), ('MMA', 'MMA')], default='MMA', max_length=20),
        ),
    ]
